// <copyright file="DummyWalletEntity.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Server.DataModels
{
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Represents the DummyWallet table structure for EF Core mapping.
    /// </summary>
    [Table("DummyWallets")]
    public class DummyWalletEntity
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DummyWalletEntity"/> class.
        /// </summary>
        /// <param name="buyerId">The ID of the buyer.</param>
        /// <param name="balance">The balance of the wallet.</param>
        public DummyWalletEntity(int buyerId, double balance)
        {
            this.ID = 0; // (default int value) this should be automatically generated by the DB
            this.BuyerId = buyerId;
            this.Balance = balance;
        }

        /// <summary>
        /// Gets or sets the ID of the wallet.
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// Gets or sets the ID of the buyer.
        /// </summary>
        public int BuyerId { get; set; }

        /// <summary>
        /// Gets or sets the balance of the wallet.
        /// </summary>
        public double Balance { get; set; }
    }
}