// <copyright file="SellerNotificationEntity.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Server.DataModels
{
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Represents the SellerNotification table structure for EF Core mapping.
    /// </summary>
    [Table("SellerNotifications")]
    public class SellerNotificationEntity
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SellerNotificationEntity"/> class.
        /// Required by EF Core for the migrations.
        /// </summary>
        public SellerNotificationEntity()
        {
            this.NotificationMessage = string.Empty;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SellerNotificationEntity"/> class.
        /// </summary>
        /// <param name="sellerId">The ID of the seller.</param>
        /// <param name="message">The notification message.</param>
        /// <param name="followerCount">The follower count.</param>
        public SellerNotificationEntity(int sellerId, string message, int followerCount)
        {
            this.NotificationID = 0; // (default int value) this should be automatically generated by the DB
            this.SellerID = sellerId;
            this.NotificationMessage = message;
            this.NotificationFollowerCount = followerCount;
        }

        /// <summary>
        /// Gets or sets the notification ID.
        /// </summary>
        public int NotificationID { get; set; }

        /// <summary>
        /// Gets or sets the seller ID.
        /// </summary>
        public int SellerID { get; set; }

        /// <summary>
        /// Gets or sets the notification message.
        /// </summary>
        public string NotificationMessage { get; set; }

        /// <summary>
        /// Gets or sets the notification follower count.
        /// </summary>
        public int NotificationFollowerCount { get; set; }
    }
}