// <copyright file="WaitlistProductEntity.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Server.DataModels
{
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Represents the WaitlistProduct table structure for EF Core mapping.
    /// </summary>
    [Table("WaitlistProducts")]
    public class WaitlistProductEntity
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WaitlistProductEntity"/> class.
        /// Required by EF Core for the migrations.
        /// </summary>
        public WaitlistProductEntity()
        {
            this.AvailableAgain = DateTime.MinValue;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WaitlistProductEntity"/> class.
        /// </summary>
        /// <param name="productId">The ID of the product.</param>
        /// <param name="availableAgain">The date and time the product will be available again.</param>
        public WaitlistProductEntity(int productId, DateTime availableAgain)
        {
            this.WaitlistProductID = 0; // (default int value) this should be automatically generated by the DB
            this.ProductID = productId;
            this.AvailableAgain = availableAgain;
        }

        /// <summary>
        /// Gets or sets the waitlist product ID.
        /// </summary>
        public int WaitlistProductID { get; set; }

        /// <summary>
        /// Gets or sets the product ID.
        /// </summary>
        public int ProductID { get; set; }

        /// <summary>
        /// Gets or sets the date and time the product will be available again.
        /// </summary>
        public DateTime AvailableAgain { get; set; }
    }
}